#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="guest_house_database")]
public partial class ctownDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertbill(bill instance);
  partial void Updatebill(bill instance);
  partial void Deletebill(bill instance);
  partial void Insertbooking(booking instance);
  partial void Updatebooking(booking instance);
  partial void Deletebooking(booking instance);
  partial void Insertbooking_Room(booking_Room instance);
  partial void Updatebooking_Room(booking_Room instance);
  partial void Deletebooking_Room(booking_Room instance);
  partial void Insertbranch(branch instance);
  partial void Updatebranch(branch instance);
  partial void Deletebranch(branch instance);
  partial void InsertBranch_asset(Branch_asset instance);
  partial void UpdateBranch_asset(Branch_asset instance);
  partial void DeleteBranch_asset(Branch_asset instance);
  partial void Insertemployee(employee instance);
  partial void Updateemployee(employee instance);
  partial void Deleteemployee(employee instance);
  partial void Insertfacility_payment(facility_payment instance);
  partial void Updatefacility_payment(facility_payment instance);
  partial void Deletefacility_payment(facility_payment instance);
  partial void Insertforeigner(foreigner instance);
  partial void Updateforeigner(foreigner instance);
  partial void Deleteforeigner(foreigner instance);
  partial void Insertguest(guest instance);
  partial void Updateguest(guest instance);
  partial void Deleteguest(guest instance);
  partial void Insertimage(image instance);
  partial void Updateimage(image instance);
  partial void Deleteimage(image instance);
  partial void Insertother_requirement(other_requirement instance);
  partial void Updateother_requirement(other_requirement instance);
  partial void Deleteother_requirement(other_requirement instance);
  partial void Insertroom_asset(room_asset instance);
  partial void Updateroom_asset(room_asset instance);
  partial void Deleteroom_asset(room_asset instance);
  partial void Insertroom_service_menu(room_service_menu instance);
  partial void Updateroom_service_menu(room_service_menu instance);
  partial void Deleteroom_service_menu(room_service_menu instance);
  partial void Insertroom(room instance);
  partial void Updateroom(room instance);
  partial void Deleteroom(room instance);
  partial void Inserttotal_payment(total_payment instance);
  partial void Updatetotal_payment(total_payment instance);
  partial void Deletetotal_payment(total_payment instance);
  partial void Insertplaced_order(placed_order instance);
  partial void Updateplaced_order(placed_order instance);
  partial void Deleteplaced_order(placed_order instance);
  partial void Insertevent_calender(event_calender instance);
  partial void Updateevent_calender(event_calender instance);
  partial void Deleteevent_calender(event_calender instance);
  #endregion
	
	public ctownDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["guest_house_databaseConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ctownDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ctownDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ctownDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ctownDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<bill> bills
	{
		get
		{
			return this.GetTable<bill>();
		}
	}
	
	public System.Data.Linq.Table<booking> bookings
	{
		get
		{
			return this.GetTable<booking>();
		}
	}
	
	public System.Data.Linq.Table<booking_Room> booking_Rooms
	{
		get
		{
			return this.GetTable<booking_Room>();
		}
	}
	
	public System.Data.Linq.Table<branch> branches
	{
		get
		{
			return this.GetTable<branch>();
		}
	}
	
	public System.Data.Linq.Table<Branch_asset> Branch_assets
	{
		get
		{
			return this.GetTable<Branch_asset>();
		}
	}
	
	public System.Data.Linq.Table<employee> employees
	{
		get
		{
			return this.GetTable<employee>();
		}
	}
	
	public System.Data.Linq.Table<facility_payment> facility_payments
	{
		get
		{
			return this.GetTable<facility_payment>();
		}
	}
	
	public System.Data.Linq.Table<foreigner> foreigners
	{
		get
		{
			return this.GetTable<foreigner>();
		}
	}
	
	public System.Data.Linq.Table<guest> guests
	{
		get
		{
			return this.GetTable<guest>();
		}
	}
	
	public System.Data.Linq.Table<image> images
	{
		get
		{
			return this.GetTable<image>();
		}
	}
	
	public System.Data.Linq.Table<other_requirement> other_requirements
	{
		get
		{
			return this.GetTable<other_requirement>();
		}
	}
	
	public System.Data.Linq.Table<room_asset> room_assets
	{
		get
		{
			return this.GetTable<room_asset>();
		}
	}
	
	public System.Data.Linq.Table<room_service_menu> room_service_menus
	{
		get
		{
			return this.GetTable<room_service_menu>();
		}
	}
	
	public System.Data.Linq.Table<room> rooms
	{
		get
		{
			return this.GetTable<room>();
		}
	}
	
	public System.Data.Linq.Table<total_payment> total_payments
	{
		get
		{
			return this.GetTable<total_payment>();
		}
	}
	
	public System.Data.Linq.Table<placed_order> placed_orders
	{
		get
		{
			return this.GetTable<placed_order>();
		}
	}
	
	public System.Data.Linq.Table<event_calender> event_calenders
	{
		get
		{
			return this.GetTable<event_calender>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bill")]
public partial class bill : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _BillAmount;
	
	private string _BillType;
	
	private System.DateTime _Date;
	
	private int _BranchId;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBillAmountChanging(int value);
    partial void OnBillAmountChanged();
    partial void OnBillTypeChanging(string value);
    partial void OnBillTypeChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnBranchIdChanging(int value);
    partial void OnBranchIdChanged();
    #endregion
	
	public bill()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillAmount", DbType="Int NOT NULL")]
	public int BillAmount
	{
		get
		{
			return this._BillAmount;
		}
		set
		{
			if ((this._BillAmount != value))
			{
				this.OnBillAmountChanging(value);
				this.SendPropertyChanging();
				this._BillAmount = value;
				this.SendPropertyChanged("BillAmount");
				this.OnBillAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string BillType
	{
		get
		{
			return this._BillType;
		}
		set
		{
			if ((this._BillType != value))
			{
				this.OnBillTypeChanging(value);
				this.SendPropertyChanging();
				this._BillType = value;
				this.SendPropertyChanged("BillType");
				this.OnBillTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
	public System.DateTime Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchId", DbType="Int NOT NULL")]
	public int BranchId
	{
		get
		{
			return this._BranchId;
		}
		set
		{
			if ((this._BranchId != value))
			{
				this.OnBranchIdChanging(value);
				this.SendPropertyChanging();
				this._BranchId = value;
				this.SendPropertyChanged("BranchId");
				this.OnBranchIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.booking")]
public partial class booking : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _guest_id;
	
	private int _employee_id;
	
	private System.DateTime _check_in_date;
	
	private System.Nullable<System.DateTime> _check_out_date;
	
	private int _branch_id;
	
	private string _guest_reg_card_arr_date;
	
	private string _no_of_pax;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onguest_idChanging(int value);
    partial void Onguest_idChanged();
    partial void Onemployee_idChanging(int value);
    partial void Onemployee_idChanged();
    partial void Oncheck_in_dateChanging(System.DateTime value);
    partial void Oncheck_in_dateChanged();
    partial void Oncheck_out_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncheck_out_dateChanged();
    partial void Onbranch_idChanging(int value);
    partial void Onbranch_idChanged();
    partial void Onguest_reg_card_arr_dateChanging(string value);
    partial void Onguest_reg_card_arr_dateChanged();
    partial void Onno_of_paxChanging(string value);
    partial void Onno_of_paxChanged();
    #endregion
	
	public booking()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_id", DbType="Int NOT NULL")]
	public int guest_id
	{
		get
		{
			return this._guest_id;
		}
		set
		{
			if ((this._guest_id != value))
			{
				this.Onguest_idChanging(value);
				this.SendPropertyChanging();
				this._guest_id = value;
				this.SendPropertyChanged("guest_id");
				this.Onguest_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_id", DbType="Int NOT NULL")]
	public int employee_id
	{
		get
		{
			return this._employee_id;
		}
		set
		{
			if ((this._employee_id != value))
			{
				this.Onemployee_idChanging(value);
				this.SendPropertyChanging();
				this._employee_id = value;
				this.SendPropertyChanged("employee_id");
				this.Onemployee_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_check_in_date", DbType="DateTime NOT NULL")]
	public System.DateTime check_in_date
	{
		get
		{
			return this._check_in_date;
		}
		set
		{
			if ((this._check_in_date != value))
			{
				this.Oncheck_in_dateChanging(value);
				this.SendPropertyChanging();
				this._check_in_date = value;
				this.SendPropertyChanged("check_in_date");
				this.Oncheck_in_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_check_out_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> check_out_date
	{
		get
		{
			return this._check_out_date;
		}
		set
		{
			if ((this._check_out_date != value))
			{
				this.Oncheck_out_dateChanging(value);
				this.SendPropertyChanging();
				this._check_out_date = value;
				this.SendPropertyChanged("check_out_date");
				this.Oncheck_out_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branch_id", DbType="Int NOT NULL")]
	public int branch_id
	{
		get
		{
			return this._branch_id;
		}
		set
		{
			if ((this._branch_id != value))
			{
				this.Onbranch_idChanging(value);
				this.SendPropertyChanging();
				this._branch_id = value;
				this.SendPropertyChanged("branch_id");
				this.Onbranch_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_reg_card_arr_date", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string guest_reg_card_arr_date
	{
		get
		{
			return this._guest_reg_card_arr_date;
		}
		set
		{
			if ((this._guest_reg_card_arr_date != value))
			{
				this.Onguest_reg_card_arr_dateChanging(value);
				this.SendPropertyChanging();
				this._guest_reg_card_arr_date = value;
				this.SendPropertyChanged("guest_reg_card_arr_date");
				this.Onguest_reg_card_arr_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_of_pax", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string no_of_pax
	{
		get
		{
			return this._no_of_pax;
		}
		set
		{
			if ((this._no_of_pax != value))
			{
				this.Onno_of_paxChanging(value);
				this.SendPropertyChanging();
				this._no_of_pax = value;
				this.SendPropertyChanged("no_of_pax");
				this.Onno_of_paxChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.booking_Room")]
public partial class booking_Room : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private int _roomid;
	
	private string _booking_rent;
	
	private string _checkout;
	
	private int _bookingId;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnroomidChanging(int value);
    partial void OnroomidChanged();
    partial void Onbooking_rentChanging(string value);
    partial void Onbooking_rentChanged();
    partial void OncheckoutChanging(string value);
    partial void OncheckoutChanged();
    partial void OnbookingIdChanging(int value);
    partial void OnbookingIdChanged();
    #endregion
	
	public booking_Room()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roomid", DbType="Int NOT NULL")]
	public int roomid
	{
		get
		{
			return this._roomid;
		}
		set
		{
			if ((this._roomid != value))
			{
				this.OnroomidChanging(value);
				this.SendPropertyChanging();
				this._roomid = value;
				this.SendPropertyChanged("roomid");
				this.OnroomidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booking_rent", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string booking_rent
	{
		get
		{
			return this._booking_rent;
		}
		set
		{
			if ((this._booking_rent != value))
			{
				this.Onbooking_rentChanging(value);
				this.SendPropertyChanging();
				this._booking_rent = value;
				this.SendPropertyChanged("booking_rent");
				this.Onbooking_rentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkout", DbType="VarChar(50)")]
	public string checkout
	{
		get
		{
			return this._checkout;
		}
		set
		{
			if ((this._checkout != value))
			{
				this.OncheckoutChanging(value);
				this.SendPropertyChanging();
				this._checkout = value;
				this.SendPropertyChanged("checkout");
				this.OncheckoutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bookingId", DbType="Int NOT NULL")]
	public int bookingId
	{
		get
		{
			return this._bookingId;
		}
		set
		{
			if ((this._bookingId != value))
			{
				this.OnbookingIdChanging(value);
				this.SendPropertyChanging();
				this._bookingId = value;
				this.SendPropertyChanged("bookingId");
				this.OnbookingIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.branch")]
public partial class branch : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _name;
	
	private string _city;
	
	private string _country;
	
	private string _address;
	
	private string _brachno;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnbrachnoChanging(string value);
    partial void OnbrachnoChanged();
    #endregion
	
	public branch()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string country
	{
		get
		{
			return this._country;
		}
		set
		{
			if ((this._country != value))
			{
				this.OncountryChanging(value);
				this.SendPropertyChanging();
				this._country = value;
				this.SendPropertyChanged("country");
				this.OncountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brachno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string brachno
	{
		get
		{
			return this._brachno;
		}
		set
		{
			if ((this._brachno != value))
			{
				this.OnbrachnoChanging(value);
				this.SendPropertyChanging();
				this._brachno = value;
				this.SendPropertyChanged("brachno");
				this.OnbrachnoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Branch_assets")]
public partial class Branch_asset : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _title;
	
	private string _description;
	
	private int _no_item;
	
	private int _bid;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onno_itemChanging(int value);
    partial void Onno_itemChanged();
    partial void OnbidChanging(int value);
    partial void OnbidChanged();
    #endregion
	
	public Branch_asset()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_item", DbType="Int NOT NULL")]
	public int no_item
	{
		get
		{
			return this._no_item;
		}
		set
		{
			if ((this._no_item != value))
			{
				this.Onno_itemChanging(value);
				this.SendPropertyChanging();
				this._no_item = value;
				this.SendPropertyChanged("no_item");
				this.Onno_itemChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bid", DbType="Int NOT NULL")]
	public int bid
	{
		get
		{
			return this._bid;
		}
		set
		{
			if ((this._bid != value))
			{
				this.OnbidChanging(value);
				this.SendPropertyChanging();
				this._bid = value;
				this.SendPropertyChanged("bid");
				this.OnbidChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.employee")]
public partial class employee : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _name;
	
	private string _email;
	
	private string _employee_no;
	
	private string _cnic;
	
	private string _designation;
	
	private System.Data.Linq.Binary _image;
	
	private int _branch_id;
	
	private System.Nullable<int> _block_client;
	
	private string _username;
	
	private string _password;
	
	private string _login_type;
	
	private System.Nullable<System.DateTime> _dateofjoining;
	
	private string _address;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onemployee_noChanging(string value);
    partial void Onemployee_noChanged();
    partial void OncnicChanging(string value);
    partial void OncnicChanged();
    partial void OndesignationChanging(string value);
    partial void OndesignationChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void Onbranch_idChanging(int value);
    partial void Onbranch_idChanged();
    partial void Onblock_clientChanging(System.Nullable<int> value);
    partial void Onblock_clientChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onlogin_typeChanging(string value);
    partial void Onlogin_typeChanged();
    partial void OndateofjoiningChanging(System.Nullable<System.DateTime> value);
    partial void OndateofjoiningChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    #endregion
	
	public employee()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_no", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string employee_no
	{
		get
		{
			return this._employee_no;
		}
		set
		{
			if ((this._employee_no != value))
			{
				this.Onemployee_noChanging(value);
				this.SendPropertyChanging();
				this._employee_no = value;
				this.SendPropertyChanged("employee_no");
				this.Onemployee_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnic", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string cnic
	{
		get
		{
			return this._cnic;
		}
		set
		{
			if ((this._cnic != value))
			{
				this.OncnicChanging(value);
				this.SendPropertyChanging();
				this._cnic = value;
				this.SendPropertyChanged("cnic");
				this.OncnicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designation", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string designation
	{
		get
		{
			return this._designation;
		}
		set
		{
			if ((this._designation != value))
			{
				this.OndesignationChanging(value);
				this.SendPropertyChanging();
				this._designation = value;
				this.SendPropertyChanged("designation");
				this.OndesignationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary image
	{
		get
		{
			return this._image;
		}
		set
		{
			if ((this._image != value))
			{
				this.OnimageChanging(value);
				this.SendPropertyChanging();
				this._image = value;
				this.SendPropertyChanged("image");
				this.OnimageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branch_id", DbType="Int NOT NULL")]
	public int branch_id
	{
		get
		{
			return this._branch_id;
		}
		set
		{
			if ((this._branch_id != value))
			{
				this.Onbranch_idChanging(value);
				this.SendPropertyChanging();
				this._branch_id = value;
				this.SendPropertyChanged("branch_id");
				this.Onbranch_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_block_client", DbType="Int")]
	public System.Nullable<int> block_client
	{
		get
		{
			return this._block_client;
		}
		set
		{
			if ((this._block_client != value))
			{
				this.Onblock_clientChanging(value);
				this.SendPropertyChanging();
				this._block_client = value;
				this.SendPropertyChanged("block_client");
				this.Onblock_clientChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_type", DbType="NVarChar(50)")]
	public string login_type
	{
		get
		{
			return this._login_type;
		}
		set
		{
			if ((this._login_type != value))
			{
				this.Onlogin_typeChanging(value);
				this.SendPropertyChanging();
				this._login_type = value;
				this.SendPropertyChanged("login_type");
				this.Onlogin_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateofjoining", DbType="DateTime")]
	public System.Nullable<System.DateTime> dateofjoining
	{
		get
		{
			return this._dateofjoining;
		}
		set
		{
			if ((this._dateofjoining != value))
			{
				this.OndateofjoiningChanging(value);
				this.SendPropertyChanging();
				this._dateofjoining = value;
				this.SendPropertyChanged("dateofjoining");
				this.OndateofjoiningChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(150)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.facility_payment")]
public partial class facility_payment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _booking_id;
	
	private string _item_detail;
	
	private string _item_cost;
	
	private System.DateTime _date_time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onbooking_idChanging(string value);
    partial void Onbooking_idChanged();
    partial void Onitem_detailChanging(string value);
    partial void Onitem_detailChanged();
    partial void Onitem_costChanging(string value);
    partial void Onitem_costChanged();
    partial void Ondate_timeChanging(System.DateTime value);
    partial void Ondate_timeChanged();
    #endregion
	
	public facility_payment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booking_id", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string booking_id
	{
		get
		{
			return this._booking_id;
		}
		set
		{
			if ((this._booking_id != value))
			{
				this.Onbooking_idChanging(value);
				this.SendPropertyChanging();
				this._booking_id = value;
				this.SendPropertyChanged("booking_id");
				this.Onbooking_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_detail", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string item_detail
	{
		get
		{
			return this._item_detail;
		}
		set
		{
			if ((this._item_detail != value))
			{
				this.Onitem_detailChanging(value);
				this.SendPropertyChanging();
				this._item_detail = value;
				this.SendPropertyChanged("item_detail");
				this.Onitem_detailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_cost", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string item_cost
	{
		get
		{
			return this._item_cost;
		}
		set
		{
			if ((this._item_cost != value))
			{
				this.Onitem_costChanging(value);
				this.SendPropertyChanging();
				this._item_cost = value;
				this.SendPropertyChanged("item_cost");
				this.Onitem_costChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime NOT NULL")]
	public System.DateTime date_time
	{
		get
		{
			return this._date_time;
		}
		set
		{
			if ((this._date_time != value))
			{
				this.Ondate_timeChanging(value);
				this.SendPropertyChanging();
				this._date_time = value;
				this.SendPropertyChanged("date_time");
				this.Ondate_timeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.foreigners")]
public partial class foreigner : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _guest_id;
	
	private string _passport_no;
	
	private string _nationality;
	
	private string _issue_date;
	
	private string _visa_number;
	
	private System.DateTime _valid_upto;
	
	private string _purpose_of_visit;
	
	private string _coming_from;
	
	private string _going_to;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onguest_idChanging(string value);
    partial void Onguest_idChanged();
    partial void Onpassport_noChanging(string value);
    partial void Onpassport_noChanged();
    partial void OnnationalityChanging(string value);
    partial void OnnationalityChanged();
    partial void Onissue_dateChanging(string value);
    partial void Onissue_dateChanged();
    partial void Onvisa_numberChanging(string value);
    partial void Onvisa_numberChanged();
    partial void Onvalid_uptoChanging(System.DateTime value);
    partial void Onvalid_uptoChanged();
    partial void Onpurpose_of_visitChanging(string value);
    partial void Onpurpose_of_visitChanged();
    partial void Oncoming_fromChanging(string value);
    partial void Oncoming_fromChanged();
    partial void Ongoing_toChanging(string value);
    partial void Ongoing_toChanged();
    #endregion
	
	public foreigner()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_id", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string guest_id
	{
		get
		{
			return this._guest_id;
		}
		set
		{
			if ((this._guest_id != value))
			{
				this.Onguest_idChanging(value);
				this.SendPropertyChanging();
				this._guest_id = value;
				this.SendPropertyChanged("guest_id");
				this.Onguest_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passport_no", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string passport_no
	{
		get
		{
			return this._passport_no;
		}
		set
		{
			if ((this._passport_no != value))
			{
				this.Onpassport_noChanging(value);
				this.SendPropertyChanging();
				this._passport_no = value;
				this.SendPropertyChanged("passport_no");
				this.Onpassport_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string nationality
	{
		get
		{
			return this._nationality;
		}
		set
		{
			if ((this._nationality != value))
			{
				this.OnnationalityChanging(value);
				this.SendPropertyChanging();
				this._nationality = value;
				this.SendPropertyChanged("nationality");
				this.OnnationalityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_issue_date", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string issue_date
	{
		get
		{
			return this._issue_date;
		}
		set
		{
			if ((this._issue_date != value))
			{
				this.Onissue_dateChanging(value);
				this.SendPropertyChanging();
				this._issue_date = value;
				this.SendPropertyChanged("issue_date");
				this.Onissue_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visa_number", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string visa_number
	{
		get
		{
			return this._visa_number;
		}
		set
		{
			if ((this._visa_number != value))
			{
				this.Onvisa_numberChanging(value);
				this.SendPropertyChanging();
				this._visa_number = value;
				this.SendPropertyChanged("visa_number");
				this.Onvisa_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valid_upto", DbType="DateTime NOT NULL")]
	public System.DateTime valid_upto
	{
		get
		{
			return this._valid_upto;
		}
		set
		{
			if ((this._valid_upto != value))
			{
				this.Onvalid_uptoChanging(value);
				this.SendPropertyChanging();
				this._valid_upto = value;
				this.SendPropertyChanged("valid_upto");
				this.Onvalid_uptoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_purpose_of_visit", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string purpose_of_visit
	{
		get
		{
			return this._purpose_of_visit;
		}
		set
		{
			if ((this._purpose_of_visit != value))
			{
				this.Onpurpose_of_visitChanging(value);
				this.SendPropertyChanging();
				this._purpose_of_visit = value;
				this.SendPropertyChanged("purpose_of_visit");
				this.Onpurpose_of_visitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coming_from", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string coming_from
	{
		get
		{
			return this._coming_from;
		}
		set
		{
			if ((this._coming_from != value))
			{
				this.Oncoming_fromChanging(value);
				this.SendPropertyChanging();
				this._coming_from = value;
				this.SendPropertyChanged("coming_from");
				this.Oncoming_fromChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_going_to", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string going_to
	{
		get
		{
			return this._going_to;
		}
		set
		{
			if ((this._going_to != value))
			{
				this.Ongoing_toChanging(value);
				this.SendPropertyChanging();
				this._going_to = value;
				this.SendPropertyChanged("going_to");
				this.Ongoing_toChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.guests")]
public partial class guest : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _reg_no;
	
	private string _guest_name;
	
	private string _cnic;
	
	private System.DateTime _date_of_birth;
	
	private string _company_name;
	
	private string _complete__address;
	
	private string _profession;
	
	private string _designation;
	
	private string _permanent_address;
	
	private string _office_phone;
	
	private string _residence;
	
	private string _mobile;
	
	private string _f_passport_no;
	
	private string _f_nationality;
	
	private System.Nullable<System.DateTime> _f_passport_issue_date;
	
	private string _f_visa_number;
	
	private System.Nullable<System.DateTime> _f_visa_valid_upto;
	
	private string _f_purpose_of_vist;
	
	private string _f_coming_from;
	
	private string _f_going_to;
	
	private System.Nullable<System.DateTime> _departure_date;
	
	private string _flight_no;
	
	private string _place_of_issue;
	
	private string _guest_type;
	
	private System.Data.Linq.Binary _image;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onreg_noChanging(string value);
    partial void Onreg_noChanged();
    partial void Onguest_nameChanging(string value);
    partial void Onguest_nameChanged();
    partial void OncnicChanging(string value);
    partial void OncnicChanged();
    partial void Ondate_of_birthChanging(System.DateTime value);
    partial void Ondate_of_birthChanged();
    partial void Oncompany_nameChanging(string value);
    partial void Oncompany_nameChanged();
    partial void Oncomplete__addressChanging(string value);
    partial void Oncomplete__addressChanged();
    partial void OnprofessionChanging(string value);
    partial void OnprofessionChanged();
    partial void OndesignationChanging(string value);
    partial void OndesignationChanged();
    partial void Onpermanent_addressChanging(string value);
    partial void Onpermanent_addressChanged();
    partial void Onoffice_phoneChanging(string value);
    partial void Onoffice_phoneChanged();
    partial void OnresidenceChanging(string value);
    partial void OnresidenceChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void Onf_passport_noChanging(string value);
    partial void Onf_passport_noChanged();
    partial void Onf_nationalityChanging(string value);
    partial void Onf_nationalityChanged();
    partial void Onf_passport_issue_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onf_passport_issue_dateChanged();
    partial void Onf_visa_numberChanging(string value);
    partial void Onf_visa_numberChanged();
    partial void Onf_visa_valid_uptoChanging(System.Nullable<System.DateTime> value);
    partial void Onf_visa_valid_uptoChanged();
    partial void Onf_purpose_of_vistChanging(string value);
    partial void Onf_purpose_of_vistChanged();
    partial void Onf_coming_fromChanging(string value);
    partial void Onf_coming_fromChanged();
    partial void Onf_going_toChanging(string value);
    partial void Onf_going_toChanged();
    partial void Ondeparture_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ondeparture_dateChanged();
    partial void Onflight_noChanging(string value);
    partial void Onflight_noChanged();
    partial void Onplace_of_issueChanging(string value);
    partial void Onplace_of_issueChanged();
    partial void Onguest_typeChanging(string value);
    partial void Onguest_typeChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    #endregion
	
	public guest()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reg_no", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string reg_no
	{
		get
		{
			return this._reg_no;
		}
		set
		{
			if ((this._reg_no != value))
			{
				this.Onreg_noChanging(value);
				this.SendPropertyChanging();
				this._reg_no = value;
				this.SendPropertyChanged("reg_no");
				this.Onreg_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_name", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string guest_name
	{
		get
		{
			return this._guest_name;
		}
		set
		{
			if ((this._guest_name != value))
			{
				this.Onguest_nameChanging(value);
				this.SendPropertyChanging();
				this._guest_name = value;
				this.SendPropertyChanged("guest_name");
				this.Onguest_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnic", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string cnic
	{
		get
		{
			return this._cnic;
		}
		set
		{
			if ((this._cnic != value))
			{
				this.OncnicChanging(value);
				this.SendPropertyChanging();
				this._cnic = value;
				this.SendPropertyChanged("cnic");
				this.OncnicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="Date NOT NULL")]
	public System.DateTime date_of_birth
	{
		get
		{
			return this._date_of_birth;
		}
		set
		{
			if ((this._date_of_birth != value))
			{
				this.Ondate_of_birthChanging(value);
				this.SendPropertyChanging();
				this._date_of_birth = value;
				this.SendPropertyChanged("date_of_birth");
				this.Ondate_of_birthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="NVarChar(25)")]
	public string company_name
	{
		get
		{
			return this._company_name;
		}
		set
		{
			if ((this._company_name != value))
			{
				this.Oncompany_nameChanging(value);
				this.SendPropertyChanging();
				this._company_name = value;
				this.SendPropertyChanged("company_name");
				this.Oncompany_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[complete _address]", Storage="_complete__address", DbType="NVarChar(50)")]
	public string complete__address
	{
		get
		{
			return this._complete__address;
		}
		set
		{
			if ((this._complete__address != value))
			{
				this.Oncomplete__addressChanging(value);
				this.SendPropertyChanging();
				this._complete__address = value;
				this.SendPropertyChanged("complete__address");
				this.Oncomplete__addressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profession", DbType="NVarChar(25)")]
	public string profession
	{
		get
		{
			return this._profession;
		}
		set
		{
			if ((this._profession != value))
			{
				this.OnprofessionChanging(value);
				this.SendPropertyChanging();
				this._profession = value;
				this.SendPropertyChanged("profession");
				this.OnprofessionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designation", DbType="NVarChar(25)")]
	public string designation
	{
		get
		{
			return this._designation;
		}
		set
		{
			if ((this._designation != value))
			{
				this.OndesignationChanging(value);
				this.SendPropertyChanging();
				this._designation = value;
				this.SendPropertyChanged("designation");
				this.OndesignationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permanent_address", DbType="NVarChar(50)")]
	public string permanent_address
	{
		get
		{
			return this._permanent_address;
		}
		set
		{
			if ((this._permanent_address != value))
			{
				this.Onpermanent_addressChanging(value);
				this.SendPropertyChanging();
				this._permanent_address = value;
				this.SendPropertyChanged("permanent_address");
				this.Onpermanent_addressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_office_phone", DbType="NVarChar(25)")]
	public string office_phone
	{
		get
		{
			return this._office_phone;
		}
		set
		{
			if ((this._office_phone != value))
			{
				this.Onoffice_phoneChanging(value);
				this.SendPropertyChanging();
				this._office_phone = value;
				this.SendPropertyChanged("office_phone");
				this.Onoffice_phoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_residence", DbType="NVarChar(25)")]
	public string residence
	{
		get
		{
			return this._residence;
		}
		set
		{
			if ((this._residence != value))
			{
				this.OnresidenceChanging(value);
				this.SendPropertyChanging();
				this._residence = value;
				this.SendPropertyChanged("residence");
				this.OnresidenceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NVarChar(25)")]
	public string mobile
	{
		get
		{
			return this._mobile;
		}
		set
		{
			if ((this._mobile != value))
			{
				this.OnmobileChanging(value);
				this.SendPropertyChanging();
				this._mobile = value;
				this.SendPropertyChanged("mobile");
				this.OnmobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_passport_no", DbType="VarChar(50)")]
	public string f_passport_no
	{
		get
		{
			return this._f_passport_no;
		}
		set
		{
			if ((this._f_passport_no != value))
			{
				this.Onf_passport_noChanging(value);
				this.SendPropertyChanging();
				this._f_passport_no = value;
				this.SendPropertyChanged("f_passport_no");
				this.Onf_passport_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_nationality", DbType="VarChar(50)")]
	public string f_nationality
	{
		get
		{
			return this._f_nationality;
		}
		set
		{
			if ((this._f_nationality != value))
			{
				this.Onf_nationalityChanging(value);
				this.SendPropertyChanging();
				this._f_nationality = value;
				this.SendPropertyChanged("f_nationality");
				this.Onf_nationalityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_passport_issue_date", DbType="Date")]
	public System.Nullable<System.DateTime> f_passport_issue_date
	{
		get
		{
			return this._f_passport_issue_date;
		}
		set
		{
			if ((this._f_passport_issue_date != value))
			{
				this.Onf_passport_issue_dateChanging(value);
				this.SendPropertyChanging();
				this._f_passport_issue_date = value;
				this.SendPropertyChanged("f_passport_issue_date");
				this.Onf_passport_issue_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_visa_number", DbType="VarChar(50)")]
	public string f_visa_number
	{
		get
		{
			return this._f_visa_number;
		}
		set
		{
			if ((this._f_visa_number != value))
			{
				this.Onf_visa_numberChanging(value);
				this.SendPropertyChanging();
				this._f_visa_number = value;
				this.SendPropertyChanged("f_visa_number");
				this.Onf_visa_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_visa_valid_upto", DbType="Date")]
	public System.Nullable<System.DateTime> f_visa_valid_upto
	{
		get
		{
			return this._f_visa_valid_upto;
		}
		set
		{
			if ((this._f_visa_valid_upto != value))
			{
				this.Onf_visa_valid_uptoChanging(value);
				this.SendPropertyChanging();
				this._f_visa_valid_upto = value;
				this.SendPropertyChanged("f_visa_valid_upto");
				this.Onf_visa_valid_uptoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_purpose_of_vist", DbType="VarChar(50)")]
	public string f_purpose_of_vist
	{
		get
		{
			return this._f_purpose_of_vist;
		}
		set
		{
			if ((this._f_purpose_of_vist != value))
			{
				this.Onf_purpose_of_vistChanging(value);
				this.SendPropertyChanging();
				this._f_purpose_of_vist = value;
				this.SendPropertyChanged("f_purpose_of_vist");
				this.Onf_purpose_of_vistChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_coming_from", DbType="VarChar(50)")]
	public string f_coming_from
	{
		get
		{
			return this._f_coming_from;
		}
		set
		{
			if ((this._f_coming_from != value))
			{
				this.Onf_coming_fromChanging(value);
				this.SendPropertyChanging();
				this._f_coming_from = value;
				this.SendPropertyChanged("f_coming_from");
				this.Onf_coming_fromChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_going_to", DbType="VarChar(50)")]
	public string f_going_to
	{
		get
		{
			return this._f_going_to;
		}
		set
		{
			if ((this._f_going_to != value))
			{
				this.Onf_going_toChanging(value);
				this.SendPropertyChanging();
				this._f_going_to = value;
				this.SendPropertyChanged("f_going_to");
				this.Onf_going_toChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departure_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> departure_date
	{
		get
		{
			return this._departure_date;
		}
		set
		{
			if ((this._departure_date != value))
			{
				this.Ondeparture_dateChanging(value);
				this.SendPropertyChanging();
				this._departure_date = value;
				this.SendPropertyChanged("departure_date");
				this.Ondeparture_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_no", DbType="VarChar(50)")]
	public string flight_no
	{
		get
		{
			return this._flight_no;
		}
		set
		{
			if ((this._flight_no != value))
			{
				this.Onflight_noChanging(value);
				this.SendPropertyChanging();
				this._flight_no = value;
				this.SendPropertyChanged("flight_no");
				this.Onflight_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_place_of_issue", DbType="VarChar(50)")]
	public string place_of_issue
	{
		get
		{
			return this._place_of_issue;
		}
		set
		{
			if ((this._place_of_issue != value))
			{
				this.Onplace_of_issueChanging(value);
				this.SendPropertyChanging();
				this._place_of_issue = value;
				this.SendPropertyChanged("place_of_issue");
				this.Onplace_of_issueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_type", DbType="VarChar(50)")]
	public string guest_type
	{
		get
		{
			return this._guest_type;
		}
		set
		{
			if ((this._guest_type != value))
			{
				this.Onguest_typeChanging(value);
				this.SendPropertyChanging();
				this._guest_type = value;
				this.SendPropertyChanged("guest_type");
				this.Onguest_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary image
	{
		get
		{
			return this._image;
		}
		set
		{
			if ((this._image != value))
			{
				this.OnimageChanging(value);
				this.SendPropertyChanging();
				this._image = value;
				this.SendPropertyChanged("image");
				this.OnimageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.images")]
public partial class image : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _room_id;
	
	private System.Data.Linq.Binary _image1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onroom_idChanging(string value);
    partial void Onroom_idChanged();
    partial void Onimage1Changing(System.Data.Linq.Binary value);
    partial void Onimage1Changed();
    #endregion
	
	public image()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_id", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string room_id
	{
		get
		{
			return this._room_id;
		}
		set
		{
			if ((this._room_id != value))
			{
				this.Onroom_idChanging(value);
				this.SendPropertyChanging();
				this._room_id = value;
				this.SendPropertyChanged("room_id");
				this.Onroom_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="image", Storage="_image1", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary image1
	{
		get
		{
			return this._image1;
		}
		set
		{
			if ((this._image1 != value))
			{
				this.Onimage1Changing(value);
				this.SendPropertyChanging();
				this._image1 = value;
				this.SendPropertyChanged("image1");
				this.Onimage1Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.other_requirement")]
public partial class other_requirement : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _newspaper;
	
	private string _other_facilities;
	
	private string _booking_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnewspaperChanging(string value);
    partial void OnnewspaperChanged();
    partial void Onother_facilitiesChanging(string value);
    partial void Onother_facilitiesChanged();
    partial void Onbooking_idChanging(string value);
    partial void Onbooking_idChanged();
    #endregion
	
	public other_requirement()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_newspaper", DbType="NVarChar(25)")]
	public string newspaper
	{
		get
		{
			return this._newspaper;
		}
		set
		{
			if ((this._newspaper != value))
			{
				this.OnnewspaperChanging(value);
				this.SendPropertyChanging();
				this._newspaper = value;
				this.SendPropertyChanged("newspaper");
				this.OnnewspaperChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other_facilities", DbType="NVarChar(25)")]
	public string other_facilities
	{
		get
		{
			return this._other_facilities;
		}
		set
		{
			if ((this._other_facilities != value))
			{
				this.Onother_facilitiesChanging(value);
				this.SendPropertyChanging();
				this._other_facilities = value;
				this.SendPropertyChanged("other_facilities");
				this.Onother_facilitiesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booking_id", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string booking_id
	{
		get
		{
			return this._booking_id;
		}
		set
		{
			if ((this._booking_id != value))
			{
				this.Onbooking_idChanging(value);
				this.SendPropertyChanging();
				this._booking_id = value;
				this.SendPropertyChanged("booking_id");
				this.Onbooking_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.room_assets")]
public partial class room_asset : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private int _room_id;
	
	private string _label;
	
	private string _description;
	
	private int _total_item;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onroom_idChanging(int value);
    partial void Onroom_idChanged();
    partial void OnlabelChanging(string value);
    partial void OnlabelChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Ontotal_itemChanging(int value);
    partial void Ontotal_itemChanged();
    #endregion
	
	public room_asset()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_id", DbType="Int NOT NULL")]
	public int room_id
	{
		get
		{
			return this._room_id;
		}
		set
		{
			if ((this._room_id != value))
			{
				this.Onroom_idChanging(value);
				this.SendPropertyChanging();
				this._room_id = value;
				this.SendPropertyChanged("room_id");
				this.Onroom_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_label", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string label
	{
		get
		{
			return this._label;
		}
		set
		{
			if ((this._label != value))
			{
				this.OnlabelChanging(value);
				this.SendPropertyChanging();
				this._label = value;
				this.SendPropertyChanged("label");
				this.OnlabelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_item", DbType="Int NOT NULL")]
	public int total_item
	{
		get
		{
			return this._total_item;
		}
		set
		{
			if ((this._total_item != value))
			{
				this.Ontotal_itemChanging(value);
				this.SendPropertyChanging();
				this._total_item = value;
				this.SendPropertyChanged("total_item");
				this.Ontotal_itemChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.room_service_menu")]
public partial class room_service_menu : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _type;
	
	private string _item_name;
	
	private int _price;
	
	private string _quantity;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Onitem_nameChanging(string value);
    partial void Onitem_nameChanged();
    partial void OnpriceChanging(int value);
    partial void OnpriceChanged();
    partial void OnquantityChanging(string value);
    partial void OnquantityChanged();
    #endregion
	
	public room_service_menu()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string item_name
	{
		get
		{
			return this._item_name;
		}
		set
		{
			if ((this._item_name != value))
			{
				this.Onitem_nameChanging(value);
				this.SendPropertyChanging();
				this._item_name = value;
				this.SendPropertyChanged("item_name");
				this.Onitem_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int NOT NULL")]
	public int price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="NVarChar(25)")]
	public string quantity
	{
		get
		{
			return this._quantity;
		}
		set
		{
			if ((this._quantity != value))
			{
				this.OnquantityChanging(value);
				this.SendPropertyChanging();
				this._quantity = value;
				this.SendPropertyChanged("quantity");
				this.OnquantityChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rooms")]
public partial class room : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _room_no;
	
	private string _room_type;
	
	private string _room_size;
	
	private string _maximum_room_rent;
	
	private string _minimum_room_rent;
	
	private int _branch_id;
	
	private string _availbilty;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onroom_noChanging(string value);
    partial void Onroom_noChanged();
    partial void Onroom_typeChanging(string value);
    partial void Onroom_typeChanged();
    partial void Onroom_sizeChanging(string value);
    partial void Onroom_sizeChanged();
    partial void Onmaximum_room_rentChanging(string value);
    partial void Onmaximum_room_rentChanged();
    partial void Onminimum_room_rentChanging(string value);
    partial void Onminimum_room_rentChanged();
    partial void Onbranch_idChanging(int value);
    partial void Onbranch_idChanged();
    partial void OnavailbiltyChanging(string value);
    partial void OnavailbiltyChanged();
    #endregion
	
	public room()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_no", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string room_no
	{
		get
		{
			return this._room_no;
		}
		set
		{
			if ((this._room_no != value))
			{
				this.Onroom_noChanging(value);
				this.SendPropertyChanging();
				this._room_no = value;
				this.SendPropertyChanged("room_no");
				this.Onroom_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_type", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string room_type
	{
		get
		{
			return this._room_type;
		}
		set
		{
			if ((this._room_type != value))
			{
				this.Onroom_typeChanging(value);
				this.SendPropertyChanging();
				this._room_type = value;
				this.SendPropertyChanged("room_type");
				this.Onroom_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_size", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string room_size
	{
		get
		{
			return this._room_size;
		}
		set
		{
			if ((this._room_size != value))
			{
				this.Onroom_sizeChanging(value);
				this.SendPropertyChanging();
				this._room_size = value;
				this.SendPropertyChanged("room_size");
				this.Onroom_sizeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maximum_room_rent", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string maximum_room_rent
	{
		get
		{
			return this._maximum_room_rent;
		}
		set
		{
			if ((this._maximum_room_rent != value))
			{
				this.Onmaximum_room_rentChanging(value);
				this.SendPropertyChanging();
				this._maximum_room_rent = value;
				this.SendPropertyChanged("maximum_room_rent");
				this.Onmaximum_room_rentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minimum_room_rent", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string minimum_room_rent
	{
		get
		{
			return this._minimum_room_rent;
		}
		set
		{
			if ((this._minimum_room_rent != value))
			{
				this.Onminimum_room_rentChanging(value);
				this.SendPropertyChanging();
				this._minimum_room_rent = value;
				this.SendPropertyChanged("minimum_room_rent");
				this.Onminimum_room_rentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branch_id", DbType="Int NOT NULL")]
	public int branch_id
	{
		get
		{
			return this._branch_id;
		}
		set
		{
			if ((this._branch_id != value))
			{
				this.Onbranch_idChanging(value);
				this.SendPropertyChanging();
				this._branch_id = value;
				this.SendPropertyChanged("branch_id");
				this.Onbranch_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_availbilty", DbType="VarChar(10)")]
	public string availbilty
	{
		get
		{
			return this._availbilty;
		}
		set
		{
			if ((this._availbilty != value))
			{
				this.OnavailbiltyChanging(value);
				this.SendPropertyChanging();
				this._availbilty = value;
				this.SendPropertyChanged("availbilty");
				this.OnavailbiltyChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.total_payment")]
public partial class total_payment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _booking_id;
	
	private string _total_rent;
	
	private string _facility_total_payment;
	
	private string _total_bill;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onbooking_idChanging(string value);
    partial void Onbooking_idChanged();
    partial void Ontotal_rentChanging(string value);
    partial void Ontotal_rentChanged();
    partial void Onfacility_total_paymentChanging(string value);
    partial void Onfacility_total_paymentChanged();
    partial void Ontotal_billChanging(string value);
    partial void Ontotal_billChanged();
    #endregion
	
	public total_payment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booking_id", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string booking_id
	{
		get
		{
			return this._booking_id;
		}
		set
		{
			if ((this._booking_id != value))
			{
				this.Onbooking_idChanging(value);
				this.SendPropertyChanging();
				this._booking_id = value;
				this.SendPropertyChanged("booking_id");
				this.Onbooking_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_rent", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string total_rent
	{
		get
		{
			return this._total_rent;
		}
		set
		{
			if ((this._total_rent != value))
			{
				this.Ontotal_rentChanging(value);
				this.SendPropertyChanging();
				this._total_rent = value;
				this.SendPropertyChanged("total_rent");
				this.Ontotal_rentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facility_total_payment", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string facility_total_payment
	{
		get
		{
			return this._facility_total_payment;
		}
		set
		{
			if ((this._facility_total_payment != value))
			{
				this.Onfacility_total_paymentChanging(value);
				this.SendPropertyChanging();
				this._facility_total_payment = value;
				this.SendPropertyChanged("facility_total_payment");
				this.Onfacility_total_paymentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_bill", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string total_bill
	{
		get
		{
			return this._total_bill;
		}
		set
		{
			if ((this._total_bill != value))
			{
				this.Ontotal_billChanging(value);
				this.SendPropertyChanging();
				this._total_bill = value;
				this.SendPropertyChanged("total_bill");
				this.Ontotal_billChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.placed_order")]
public partial class placed_order : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _booking_id;
	
	private int _item_id;
	
	private int _quantity;
	
	private string _delivery;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onbooking_idChanging(int value);
    partial void Onbooking_idChanged();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    partial void OndeliveryChanging(string value);
    partial void OndeliveryChanged();
    #endregion
	
	public placed_order()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booking_id", DbType="Int NOT NULL")]
	public int booking_id
	{
		get
		{
			return this._booking_id;
		}
		set
		{
			if ((this._booking_id != value))
			{
				this.Onbooking_idChanging(value);
				this.SendPropertyChanging();
				this._booking_id = value;
				this.SendPropertyChanged("booking_id");
				this.Onbooking_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", DbType="Int NOT NULL")]
	public int item_id
	{
		get
		{
			return this._item_id;
		}
		set
		{
			if ((this._item_id != value))
			{
				this.Onitem_idChanging(value);
				this.SendPropertyChanging();
				this._item_id = value;
				this.SendPropertyChanged("item_id");
				this.Onitem_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
	public int quantity
	{
		get
		{
			return this._quantity;
		}
		set
		{
			if ((this._quantity != value))
			{
				this.OnquantityChanging(value);
				this.SendPropertyChanging();
				this._quantity = value;
				this.SendPropertyChanged("quantity");
				this.OnquantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delivery", DbType="NChar(3) NOT NULL", CanBeNull=false)]
	public string delivery
	{
		get
		{
			return this._delivery;
		}
		set
		{
			if ((this._delivery != value))
			{
				this.OndeliveryChanging(value);
				this.SendPropertyChanging();
				this._delivery = value;
				this.SendPropertyChanged("delivery");
				this.OndeliveryChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.event_calender")]
public partial class event_calender : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _event_name;
	
	private string _event_description;
	
	private System.DateTime _event_start_date;
	
	private System.DateTime _event_end_date;
	
	private string _event_color;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onevent_nameChanging(string value);
    partial void Onevent_nameChanged();
    partial void Onevent_descriptionChanging(string value);
    partial void Onevent_descriptionChanged();
    partial void Onevent_start_dateChanging(System.DateTime value);
    partial void Onevent_start_dateChanged();
    partial void Onevent_end_dateChanging(System.DateTime value);
    partial void Onevent_end_dateChanged();
    partial void Onevent_colorChanging(string value);
    partial void Onevent_colorChanged();
    #endregion
	
	public event_calender()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string event_name
	{
		get
		{
			return this._event_name;
		}
		set
		{
			if ((this._event_name != value))
			{
				this.Onevent_nameChanging(value);
				this.SendPropertyChanging();
				this._event_name = value;
				this.SendPropertyChanged("event_name");
				this.Onevent_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_description", DbType="NVarChar(50)")]
	public string event_description
	{
		get
		{
			return this._event_description;
		}
		set
		{
			if ((this._event_description != value))
			{
				this.Onevent_descriptionChanging(value);
				this.SendPropertyChanging();
				this._event_description = value;
				this.SendPropertyChanged("event_description");
				this.Onevent_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_start_date", DbType="Date NOT NULL")]
	public System.DateTime event_start_date
	{
		get
		{
			return this._event_start_date;
		}
		set
		{
			if ((this._event_start_date != value))
			{
				this.Onevent_start_dateChanging(value);
				this.SendPropertyChanging();
				this._event_start_date = value;
				this.SendPropertyChanged("event_start_date");
				this.Onevent_start_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_end_date", DbType="Date NOT NULL")]
	public System.DateTime event_end_date
	{
		get
		{
			return this._event_end_date;
		}
		set
		{
			if ((this._event_end_date != value))
			{
				this.Onevent_end_dateChanging(value);
				this.SendPropertyChanging();
				this._event_end_date = value;
				this.SendPropertyChanged("event_end_date");
				this.Onevent_end_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_color", DbType="NVarChar(20)")]
	public string event_color
	{
		get
		{
			return this._event_color;
		}
		set
		{
			if ((this._event_color != value))
			{
				this.Onevent_colorChanging(value);
				this.SendPropertyChanging();
				this._event_color = value;
				this.SendPropertyChanged("event_color");
				this.Onevent_colorChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
